(define *ADMIN_ID* "{currentUserId}")
(define *SHOP1_ID* "{currentUserId}")
(define *SHOP2_ID* "{currentUserId}")
(define *BROKER_HOST* "{currentBrokerUrl}")
(define *WEBUI_HOST* "{currentWebUiUrl}")
